import {DM_Serif_Text} from "next/font/google";
import "./globals.css";

const dmSerifText = DM_Serif_Text({
  variable: "--font-dmSerifText",
  subsets: ["latin"],
});


export const metadata = {
  title: "My Job Board",
  description: "Generated by DevAndi",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${DM_Serif_Text.className} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
