import {DM_Serif_Text} from "next/font/google";
import "./globals.css";
import Navbar from "@/components/navigation/navbar";
import Footer from "@/components/navigation/footer";

const dmSerifText = DM_Serif_Text({
  variable: "--font-dmSerifText",
  weight: ["400"],
  subsets: ["latin"],
});


export const metadata = {
  title: "My Job Board",
  description: "Generated by DevAndi",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${dmSerifText.className} antialiased`}
      >
        <Navbar />
        {children}
        <Footer />
      </body>
    </html>
  );
}
